import {
  Laptop,
  Monitor,
  FileSpreadsheet,
  Palette,
  ShieldAlert,
  Database,
  Library,
  Smartphone,
  Tablet,
  Mouse,
  Keyboard,
  Headphones,
  Webcam,
  Printer,
  HardDrive,
  Server,
  MessageSquare,
  Video,
  Code,
  PenTool,
  GitBranch,
  Cloud,
  Key,
  CreditCard,
  UserPlus,
  Package,
  Wifi,
  Mail,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  laptop: Laptop,
  monitor: Monitor,
  fileSpreadsheet: FileSpreadsheet,
  palette: Palette,
  shield: ShieldAlert,
  database: Database,
  smartphone: Smartphone,
  tablet: Tablet,
  mouse: Mouse,
  keyboard: Keyboard,
  headphones: Headphones,
  webcam: Webcam,
  printer: Printer,
  harddrive: HardDrive,
  server: Server,
  messageSquare: MessageSquare,
  video: Video,
  code: Code,
  penTool: PenTool,
  gitBranch: GitBranch,
  cloud: Cloud,
  key: Key,
  creditCard: CreditCard,
  userPlus: UserPlus,
  package: Package,
  wifi: Wifi,
  mail: Mail,
};

export default function CatalogIcon({ icon, className }: { icon?: string | null; className?: string }) {
  const Icon = (icon && MAP[icon]) || Library;
  return <Icon className={className} />;
}
